const items=[
{id:"hero-animated",title:"Animated Hero",cat:"Hero",desc:"قهرمان متحرک برای صفحه‌های معرفی و محصول.",author:"21st Community",url:"https://21st.dev/community/components/sshahaider/hero-1",tags:["React","Tailwind","Animation"]},
{id:"hero-scroll-video",title:"Scroll Video Hero",cat:"Hero",desc:"Hero ویدیویی با تعامل اسکرول.",author:"21st Community",url:"https://21st.dev/community/components/explore/nt-scroll-video-hero-prompt",tags:["Video","Scroll","Hero"]},
{id:"hero-button",title:"Hero Button Expendable",cat:"Hero",desc:"Hero تعاملی با دکمه و افکت حرکتی.",author:"shadway",url:"https://21st.dev/community/components/shadway/hero-button-expendable/default",tags:["Framer Motion","Shader"]},
{id:"card-avatar",title:"Card with Avatar",cat:"Card",desc:"کارت محتوا با تصویر و آواتار.",author:"Hero UI",url:"https://21st.dev/%40hero_ui/components/heroui-card/with-avatar",tags:["Card","Avatar","Image"]},
{id:"liquid-glass",title:"Liquid Glass Button",cat:"Button",desc:"دکمه شیشه‌ای با افکت liquid.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Button","Glass","Motion"]},
{id:"neon-button",title:"Neon Button",cat:"Button",desc:"دکمه نئونی برای رابط‌های آینده‌نگر.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Button","Neon","Glow"]},
{id:"footer",title:"Footer",cat:"Footer",desc:"فوتر برای صفحات محصول و SaaS.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Footer","Responsive"]},
{id:"header",title:"Navigation Header",cat:"Header",desc:"ناوبری واکنش‌گرا برای هدر سایت.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Navigation","Header"]},
{id:"dialog",title:"Confirm Dialog",cat:"Dialog",desc:"دیالوگ تأیید با فرم و حالت destructive.",author:"uimix",url:"https://21st.dev/community/components/uimix/one-dialog/type-to-confirm",tags:["Dialog","Form","Modal"]},
{id:"textarea",title:"Textarea with Label",cat:"Form",desc:"ورودی چندخطی با label و validation states.",author:"jshguo",url:"https://21st.dev/community/components/jshguo/interfaces-textarea/with-label",tags:["Form","Textarea","Input"]},
{id:"floating-label",title:"Floating Label",cat:"Form",desc:"فیلد ورودی با label شناور.",author:"Arihant Jain",url:"https://21st.dev/community/components/arihantcodes_1f7b8c4d/floating-label/default",tags:["Input","Form","Interactive"]},
{id:"help-button",title:"Help Button",cat:"Utility",desc:"دکمه کمک با لینک‌های اجتماعی و میانبرها.",author:"LN",url:"https://21st.dev/community/components/ln-dev7/help-button/default",tags:["Utility","Button","Menu"]},
{id:"file-trigger",title:"File Trigger",cat:"Form",desc:"انتخاب فایل با ساختار ساده و قابل استفاده.",author:"jollyshopland",url:"https://21st.dev/community/components/jollyshopland/file-trigger",tags:["File","Input","Form"]},
{id:"copy-button",title:"Copy Button Variants",cat:"Button",desc:"دکمه کپی با حالت‌های انیمیشنی.",author:"hax-design",url:"https://21st.dev/community/components/qredence/copy-button-variants/default",tags:["Copy","Button","Animation"]},
{id:"note-warning",title:"Warning Note",cat:"Feedback",desc:"پیام هشدار با action و حالت filled.",author:"shugar",url:"https://21st.dev/community/components/shugar/note/warning",tags:["Alert","Feedback","Note"]},
{id:"otp-dialog",title:"OTP Dialog",cat:"Dialog",desc:"دیالوگ تأیید کد یک‌بارمصرف.",author:"felipemenezes098",url:"https://21st.dev/community/components/felipemenezes098/the-dialog/verify-code-otp",tags:["OTP","Dialog","Auth"]},
{id:"pricing",title:"Pricing Section",cat:"Pricing",desc:"بلوک قیمت‌گذاری برای SaaS و محصولات دیجیتال.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Pricing","SaaS","Cards"]},
{id:"dashboard",title:"Dashboard",cat:"Dashboard",desc:"ساختار داشبورد برای داده و KPI.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Dashboard","Data","Grid"]},
{id:"gallery",title:"Gallery / 3D",cat:"Gallery",desc:"گالری تصویری و سه‌بعدی برای showcase.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Gallery","3D","Media"]},
{id:"testimonial",title:"Testimonials Columns",cat:"Testimonial",desc:"نمایش نظرات مشتریان در ستون‌های متحرک.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Testimonials","Social Proof"]},
{id:"search",title:"Search Bar",cat:"Navigation",desc:"نوار جست‌وجوی سریع برای آرشیوها و اپ‌ها.",author:"21st Community",url:"https://21st.dev/community/components",tags:["Search","Navigation","Input"]}
];
const cats=[...new Set(items.map(x=>x.cat))];
const grid=document.querySelector("#grid"), search=document.querySelector("#search"), filter=document.querySelector("#filter"), chips=document.querySelector("#categoryChips"), count=document.querySelector("#count"), modal=document.querySelector("#modal"), modalContent=document.querySelector("#modalContent");
function fallback(){return '<div class="fallback"><div class="shape"></div></div>'}
function render(list){count.textContent=list.length;grid.innerHTML=list.map((x,i)=>`<article class="card glass"><div class="preview">${i<12?'<iframe loading="lazy" src="'+x.url+'" title="'+x.title+'"></iframe>':fallback()}</div><div class="card-body"><div class="card-top"><span class="badge">${x.cat}</span><span class="badge">${x.author}</span></div><h3>${x.title}</h3><p>${x.desc}</p><div class="meta">${x.tags.map(t=>'<span>'+t+'</span>').join('')}</div><div class="card-actions"><button class="main" data-info="${x.id}">جزئیات / کد</button><a href="${x.url}" target="_blank" rel="noopener">منبع ↗</a></div></div></article>`).join('');document.querySelectorAll("[data-info]").forEach(b=>b.onclick=()=>openItem(items.find(x=>x.id===b.dataset.info)))}
function openItem(x){modalContent.innerHTML=`<span class="kicker">${x.cat}</span><h2>${x.title}</h2><p style="color:var(--muted)">ساخته‌شده توسط ${x.author}. برای دیدن کد و پرامپت اصلی، منبع رسمی را باز کنید.</p><div class="modal-links"><a href="${x.url}" target="_blank" rel="noopener">باز کردن صفحه 21st ↗</a><button id="copyInstall">کپی دستور نصب</button></div><pre>npx shadcn@latest add ${x.url.replace("https://21st.dev/community/components/","https://21st.dev/r/").replace("/default","")}</pre><p style="color:var(--muted);font-size:12px">این آرشیو متن کامل کد یا پرامپت شخص ثالث را دوباره منتشر نمی‌کند؛ صفحه اصلی 21st منبع کد، پرامپت و پیش‌نمایش هر قطعه است.</p>`;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.querySelector("#copyInstall").onclick=()=>navigator.clipboard?.writeText(document.querySelector("#copyInstall").parentElement.nextElementSibling.textContent)}
document.addEventListener("click",e=>{if(e.target.matches("[data-close]")){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}});document.addEventListener("keydown",e=>{if(e.key==="Escape")modal.classList.remove("open")});
cats.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;filter.appendChild(o);const b=document.createElement("button");b.className="chip";b.textContent=c;b.onclick=()=>{filter.value=c;apply()};chips.appendChild(b)});
function apply(){const q=search.value.trim().toLowerCase(),f=filter.value;render(items.filter(x=>(f==="all"||x.cat===f)&&(!q||(x.title+" "+x.cat+" "+x.desc+" "+x.tags.join(" ")).toLowerCase().includes(q))))}
search.oninput=apply;filter.onchange=apply;render(items);
document.querySelector("#themeBtn").onclick=()=>document.body.classList.toggle("dim");
